"""WhatsApp (Evolution API) inbound webhook receiver.

Receives Evolution API's messages.upsert webhook events for a specific
tenant, resolves channel identity, and publishes a message.received event
to PubSub.

Endpoint: POST /api/v1/integrations/channels/whatsapp/webhook/{tenant_id}/{webhook_secret}

Auth: Evolution API (OSS) supports neither custom outbound headers nor
HMAC-signed webhook payloads on its outbound webhook calls — confirmed
against `/webhook/set/{instance}`'s actual config schema (`enabled`, `url`,
`webhookByEvents`, `webhookBase64`, `events` only). There is no
X-Telegram-Bot-Api-Secret-Token equivalent available. The practical
security ceiling is a per-tenant random secret embedded in the URL path
(generated by IntegrationService.upsert_whatsapp_credentials and
configured as part of that tenant's own Evolution instance webhook URL) —
the only channel Evolution API actually respects when it fires the
webhook. Verified with hmac.compare_digest for constant-time comparison,
mirroring telegram_receiver.py's secret-check style even though the
transport differs (path segment instead of a header).

IP allowlisting at the reverse-proxy layer is a good *additional* hardening
layer if a tenant's Evolution instance has a fixed egress IP, but is
infrastructure-level and out of this module's scope.

Scaffold only — no linking flow yet (analogous to Telegram's link-code
flow), per MSG-004's scope. This receiver only resolves already-linked
ChannelIdentity rows and publishes message.received.
"""

from __future__ import annotations

import hashlib
import hmac
import logging
from typing import Any
from uuid import UUID

from fastapi import APIRouter, Depends, Path, Request, Response, status
from sqlalchemy.orm import Session

from app.core.db.deps import get_db
from app.core.integrations.events import MESSAGE_RECEIVED
from app.core.integrations.service import IntegrationService
from app.core.pubsub import EventPublisher, get_event_publisher
from app.core.pubsub.models import EventMetadata
from app.repositories.channel_identity_repository import ChannelIdentityRepository

logger = logging.getLogger(__name__)

router = APIRouter(tags=["whatsapp"])

_CHANNEL = "whatsapp"


def _verify_secret(path_secret: str, expected_secret: str) -> bool:
    """Constant-time comparison of the webhook URL's secret segment."""
    if not path_secret or not expected_secret:
        return False
    return hmac.compare_digest(
        hashlib.sha256(path_secret.encode()).digest(),
        hashlib.sha256(expected_secret.encode()).digest(),
    )


@router.post(
    "/channels/whatsapp/webhook/{tenant_id}/{webhook_secret}",
    status_code=status.HTTP_200_OK,
    summary="WhatsApp (Evolution API) inbound webhook",
    description=(
        "Receives Evolution API messages.upsert events for a tenant's "
        "WhatsApp instance. Authenticated via a per-tenant secret embedded "
        "in the URL path, since Evolution API supports no header/HMAC "
        "webhook auth mechanism."
    ),
)
async def whatsapp_webhook(
    request: Request,
    response: Response,
    tenant_id: UUID = Path(...),
    webhook_secret: str = Path(...),
    db: Session = Depends(get_db),
    publisher: EventPublisher = Depends(get_event_publisher),
) -> dict[str, str]:
    integration_service = IntegrationService(db)
    credentials = integration_service.get_whatsapp_credentials(tenant_id)

    if credentials is None:
        logger.warning(
            "WhatsApp webhook called for tenant %s with no WhatsApp integration configured",
            tenant_id,
        )
        response.status_code = status.HTTP_403_FORBIDDEN
        return {"detail": "whatsapp not configured for this tenant"}

    expected_secret = credentials.get("webhook_secret", "")
    if not _verify_secret(webhook_secret, expected_secret):
        response.status_code = status.HTTP_403_FORBIDDEN
        return {"detail": "invalid webhook secret"}

    try:
        payload: dict[str, Any] = await request.json()
    except Exception:
        return {"status": "ok"}

    if payload.get("event") != "messages.upsert":
        return {"status": "ok"}

    data = payload.get("data") or {}
    message = data.get("message") or {}
    text: str = message.get("conversation") or ""

    remote_jid: str = (data.get("key") or {}).get("remoteJid") or ""
    channel_user_id = remote_jid.split("@")[0] if remote_jid else ""

    if not channel_user_id:
        return {"status": "ok"}

    repo = ChannelIdentityRepository(db)
    user = repo.resolve(tenant_id, _CHANNEL, channel_user_id)
    user_id: UUID | None = UUID(str(user.id)) if user else None

    try:
        await publisher.publish(
            event_type=MESSAGE_RECEIVED,
            entity_type="message",
            entity_id=tenant_id,
            tenant_id=tenant_id,
            user_id=user_id,
            metadata=EventMetadata(
                source="whatsapp_receiver",
                additional_data={
                    "channel": _CHANNEL,
                    "channel_user_id": channel_user_id,
                    "text": text,
                },
            ),
        )
    except Exception as exc:
        logger.error("Failed to publish message.received for WhatsApp: %s", exc)

    return {"status": "ok"}
