import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("/login", "routes/login.tsx"),
  route("/forgot-password", "routes/forgot-password.tsx"),
  route("/reset-password", "routes/reset-password.tsx"),
  route("/verify-email", "routes/verify-email.tsx"),
  route("/maintenance", "routes/maintenance.tsx"),
  route("/unauthorized", "routes/unauthorized.tsx"),
  route("/dashboard", "routes/dashboard.tsx"),
  route("/users", "routes/users.tsx"),
  route("/users-create", "routes/users-create.tsx"),
  route("/users/:id", "routes/users.$id.tsx"),
  route("/users/:id/edit", "routes/users.$id.edit.tsx"),
  route("/users/:id/roles", "routes/users.$id.roles.tsx"),
  route("/users/:id/permissions", "routes/users.$id.permissions.tsx"),
  route("/profile", "routes/profile.tsx"),
  route("/settings", "routes/settings.tsx"),
  route("/files", "routes/files.tsx"),
  route("/calendar", "routes/calendar.tsx"),
  route("/tags-create", "routes/tags-create.tsx"),
  route("/calendar-create", "routes/calendar-create.tsx"),
  route("/templates-create", "routes/templates-create.tsx"),
  route("/integrations-create", "routes/integrations-create.tsx"),
  route("/automation-create", "routes/automation-create.tsx"),
  route("/search", "routes/search.tsx"),
  route("/activities", "routes/activities.tsx"),
  // Feature routes
  route("/tasks", "routes/tasks.tsx"),
  route("/tasks-create", "routes/tasks-create.tsx"),
  route("/tasks/settings", "routes/tasks.settings.tsx"),
  route("/tasks/status-customizer", "routes/tasks.status-customizer.tsx"),
  route("/tasks/webhooks", "routes/tasks.webhooks.tsx"),
  route("/tasks/:id", "routes/tasks.$id.tsx"),
  route("/tasks/:id/edit", "routes/tasks.$id.edit.tsx"),
  route("/approvals", "routes/approvals.tsx"),
  route("/approvals-create", "routes/approvals-create.tsx"),
  route("/approvals/:id", "routes/approvals.$id.tsx"),
  route("/approvals/flows/:id", "routes/approflows.$id.view.tsx"),
  route("/approvals/flows/:id/edit", "routes/approflows.$id.edit.tsx"),
  route("/automation", "routes/automation.tsx"),
  route("/automation/:id", "routes/automation.$id.tsx"),
  route("/automation/:id/edit", "routes/automation.$id.edit.tsx"),
  route("/pubsub", "routes/pubsub.tsx"),
  route("/pubsub/streams/:streamId", "routes/pubsub.streams.$streamId.tsx"),
  route("/pubsub/groups/:groupId", "routes/pubsub.groups.$groupId.tsx"),
  // Config routes
  route("/config/webhooks", "routes/config.webhooks.tsx"),
  route("/config/theme", "routes/config.theme.tsx"),
  route("/config/modules", "routes/config.modules.tsx"),
  route("/config/general", "routes/config.general.tsx"),
  route("/config/roles", "routes/config.roles.tsx"),
  route("/config/notifications", "routes/config.notifications.tsx"),
  route("/config/integrations", "routes/config.integrations.tsx"),
  route("/config/quick-actions", "routes/config.quick-actions.tsx"),
  route("/config/import-export", "routes/config.import-export.tsx"),
  route("/config/audit", "routes/config.audit.tsx"),
  route("/config/files", "routes/config.files.tsx"),
  route("/config/tenants", "routes/config.tenants.tsx"),
  route("/config/automation", "routes/config.automation.tsx"),
  route("/config/automation/analytics", "routes/config.automation.analytics.tsx"),
  route("/config/automation/digests", "routes/config.automation.digests.tsx"),
  route("/config/automation/agents", "routes/config.automation.agents.tsx"),
  route("/settings/activity-icons", "routes/settings.activity-icons.tsx"),
  route("/settings/ai-provider", "routes/settings.ai-provider.tsx"),
  // Gamification routes
  route("/gamification", "routes/gamification.tsx"),
  route("/gamification/manager", "routes/gamification.manager.tsx"),
  // Admin routes
  route("/admin/setup", "routes/admin.setup.tsx"),
  // Content & collaboration routes
  route("/comments", "routes/comments.tsx"),
  route("/notifications", "routes/notifications.tsx"),
  route("/templates", "routes/templates.tsx"),
  route("/reporting", "routes/reporting.tsx"),
  route("/workflows", "routes/workflows.tsx"),
  route("/views/filters", "routes/views.filters.tsx"),
  route("*", "routes/not-found.tsx"), // Catch-all for 404
] satisfies RouteConfig;
