/**
 * True when the activity was generated by another module as a side effect of a
 * business action (e.g. "work_order.status_changed", "lease.activo") rather than
 * authored directly by a user through this module's own create/edit form (the base
 * types: comment, call, email, meeting, task, status_change, note, file_upload,
 * custom — none of which are dot-namespaced). System-generated entries are the
 * historical record of another module and must stay immutable here even for users
 * who otherwise have activities.manage — editing/deleting them would corrupt that
 * module's own audit trail.
 */
export function isSystemGeneratedActivity(activityType: string): boolean {
  return activityType.includes(".");
}

/**
 * Human-readable fallback label for an activity_type with no matching i18n key.
 * useTranslation() returns the literal key string on a miss (not falsy), so
 * unrecognized dot-namespaced types from business modules would otherwise render
 * the raw untranslated key (e.g. "activities.types.lease.activo") in the UI.
 */
export function humanizeActivityType(activityType: string): string {
  return activityType
    .split(/[._]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export function canModifyActivity(activity: {
  activity_type: string;
}): boolean {
  return !isSystemGeneratedActivity(activity.activity_type);
}
