"""aiutox_sdk.schemas — re-exports of shared schema types.

Provides Pydantic schemas that cross module boundaries (task_status, task, etc).
"""

# Re-export all task schemas (simplified: import * from task module)
from app.schemas.task import (
    TaskAssignmentBase,
    TaskAssignmentCreate,
    TaskAssignmentResponse,
    TaskBase,
    TaskChecklistItemBase,
    TaskChecklistItemCreate,
    TaskChecklistItemResponse,
    TaskChecklistItemUpdate,
    TaskCreate,
    TaskModuleSettings,
    TaskModuleSettingsUpdate,
    TaskRecurrenceBase,
    TaskRecurrenceCreate,
    TaskRecurrenceUpdate,
    TaskReminderBase,
    TaskReminderCreate,
    TaskReminderResponse,
    TaskReminderUpdate,
    TaskResponse,
    TaskUpdate,
    WorkflowBase,
    WorkflowCreate,
    WorkflowExecutionBase,
    WorkflowExecutionCreate,
    WorkflowExecutionResponse,
    WorkflowResponse,
    WorkflowStepBase,
    WorkflowStepCreate,
    WorkflowStepResponse,
    WorkflowUpdate,
)
from app.schemas.task_status import (
    TaskStatusBase,
    TaskStatusCreate,
    TaskStatusResponse,
    TaskStatusUpdate,
)

__all__ = [
    "TaskStatusBase",
    "TaskStatusCreate",
    "TaskStatusUpdate",
    "TaskStatusResponse",
    "TaskBase",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskModuleSettings",
    "TaskModuleSettingsUpdate",
    "TaskAssignmentBase",
    "TaskAssignmentCreate",
    "TaskAssignmentResponse",
    "TaskChecklistItemBase",
    "TaskChecklistItemCreate",
    "TaskChecklistItemUpdate",
    "TaskChecklistItemResponse",
    "WorkflowBase",
    "WorkflowCreate",
    "WorkflowUpdate",
    "WorkflowResponse",
    "WorkflowStepBase",
    "WorkflowStepCreate",
    "WorkflowStepResponse",
    "WorkflowExecutionBase",
    "WorkflowExecutionCreate",
    "WorkflowExecutionResponse",
    "TaskReminderBase",
    "TaskReminderCreate",
    "TaskReminderUpdate",
    "TaskReminderResponse",
    "TaskRecurrenceBase",
    "TaskRecurrenceCreate",
    "TaskRecurrenceUpdate",
]
