"""SRC-007: add search_reindex_jobs table

Revision ID: src007_reindex_jobs
Revises: src001_search_cols
Create Date: 2026-07-19

Hand-written, not autogenerated — same rationale as
2026_07_19_src001_add_search_indices_module_id_exact_match.py: autogenerate
against this project's current head surfaces large unrelated pre-existing
schema drift. This migration only creates the new search_reindex_jobs table.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'src007_reindex_jobs'
down_revision: Union[str, None] = 'src001_search_cols'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'search_reindex_jobs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('module_id', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('last_cursor_id', sa.UUID(), nullable=True),
        sa.Column('indexed_count', sa.Integer(), nullable=False),
        sa.Column('failed_count', sa.Integer(), nullable=False),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_search_reindex_jobs_tenant_module',
        'search_reindex_jobs',
        ['tenant_id', 'module_id'],
    )
    op.create_index(
        op.f('ix_search_reindex_jobs_tenant_id'),
        'search_reindex_jobs',
        ['tenant_id'],
    )
    op.create_index(
        op.f('ix_search_reindex_jobs_module_id'),
        'search_reindex_jobs',
        ['module_id'],
    )


def downgrade() -> None:
    op.drop_index(
        op.f('ix_search_reindex_jobs_module_id'), table_name='search_reindex_jobs'
    )
    op.drop_index(
        op.f('ix_search_reindex_jobs_tenant_id'), table_name='search_reindex_jobs'
    )
    op.drop_index(
        'idx_search_reindex_jobs_tenant_module', table_name='search_reindex_jobs'
    )
    op.drop_table('search_reindex_jobs')
