"""SRC-001: add module_id and exact_match_value to search_indices

Revision ID: src001_search_cols
Revises: 8c6ae185429d
Create Date: 2026-07-19

Hand-written, not autogenerated: an `alembic revision --autogenerate` pass
against the current head surfaced ~2000 lines of unrelated pre-existing
schema drift (including DROP TABLE on several unrelated tables), a symptom
of this project's multiple independent migration branches — not caused by
this change. That output was discarded entirely; this migration only touches
`search_indices`, per docs/04-modules/core/search/MODULE-SPEC.md Section 9.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'src001_search_cols'
down_revision: Union[str, None] = '8c6ae185429d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Added nullable first, then hardened to NOT NULL after backfilling any
    # existing rows — safe regardless of whether search_indices already has
    # data (it is expected to be empty today, since nothing writes to this
    # table until SRC-003's consumer ships, but this migration does not
    # assume that without being able to verify it directly).
    op.add_column(
        'search_indices',
        sa.Column('module_id', sa.String(length=50), nullable=True),
    )
    op.execute("UPDATE search_indices SET module_id = 'unknown' WHERE module_id IS NULL")
    op.alter_column('search_indices', 'module_id', nullable=False)
    op.add_column(
        'search_indices',
        sa.Column('exact_match_value', sa.String(length=255), nullable=True),
    )
    op.create_index(
        'idx_search_indices_tenant_module',
        'search_indices',
        ['tenant_id', 'module_id'],
    )
    op.create_index(
        'idx_search_indices_tenant_exact_match',
        'search_indices',
        ['tenant_id', 'exact_match_value'],
    )


def downgrade() -> None:
    op.drop_index('idx_search_indices_tenant_exact_match', table_name='search_indices')
    op.drop_index('idx_search_indices_tenant_module', table_name='search_indices')
    op.drop_column('search_indices', 'exact_match_value')
    op.drop_column('search_indices', 'module_id')
