"""add comment_revisions table

Revision ID: ccba24a09724
Revises: 9db2067b04fd
Create Date: 2026-07-21 00:39:23.602090+00:00

Hand-written, not autogenerated: --autogenerate against this dev database
picked up ~2000 lines of pre-existing, unrelated schema drift across dozens
of other modules' tables. Only the comment_revisions table (CMT-008) is
this migration's actual concern.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccba24a09724'
down_revision: Union[str, None] = '9db2067b04fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'comment_revisions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=False),
        sa.Column('comment_id', sa.UUID(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('edited_by', sa.UUID(), nullable=True),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        'idx_comment_revisions_comment',
        'comment_revisions',
        ['comment_id', 'created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_comment_revisions_comment_id'),
        'comment_revisions',
        ['comment_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_comment_revisions_created_at'),
        'comment_revisions',
        ['created_at'],
        unique=False,
    )
    op.create_index(
        op.f('ix_comment_revisions_edited_by'),
        'comment_revisions',
        ['edited_by'],
        unique=False,
    )
    op.create_index(
        op.f('ix_comment_revisions_tenant_id'),
        'comment_revisions',
        ['tenant_id'],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f('ix_comment_revisions_tenant_id'), table_name='comment_revisions'
    )
    op.drop_index(
        op.f('ix_comment_revisions_edited_by'), table_name='comment_revisions'
    )
    op.drop_index(
        op.f('ix_comment_revisions_created_at'), table_name='comment_revisions'
    )
    op.drop_index(
        op.f('ix_comment_revisions_comment_id'), table_name='comment_revisions'
    )
    op.drop_index('idx_comment_revisions_comment', table_name='comment_revisions')
    op.drop_table('comment_revisions')
